version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  backend-engine:
    build: .
    image : native_instruments_sol
    container_name: backend-engine
    expose:
      - 5000
    ports:
      - 5000:5000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

#  elk:
#    image: sebp/elk
#    ports:
#      - "5601:5601"
#      - "9200:9200"
#      - "5044:5044"